### ISSUE TITLE
[RFC] Reduce by source node or edge

### ISSUE THREAD

**Issue by sharifza** [dmlc/dgl#1038]
## 🚀 Feature
The reduce function seems to be always happening in the destination node. It would be good to have it also on the nodes or even edges (edges can attention to their source or tail and take messages from them and get updated.).

## Motivation

Refer to this [discussion](https://discuss.dgl.ai/t/aggregation-in-the-source-node-instead-of-destination/502/2).

## Alternatives
as suggested by @mufeili one can do one of the following:
1. Add edges for both direction and manually track the ids for reversed edges and then apply send_and_recv on them. See [to_bidirected](https://docs.dgl.ai/generated/dgl.transform.to_bidirected.html#dgl.transform.to_bidirected) and [send_and_recv](https://docs.dgl.ai/generated/dgl.DGLGraph.send_and_recv.html#dgl.DGLGraph.send_and_recv).
2. Alternatively, you can directly create a reverse of the original graph and apply update_all. See [reverse](https://docs.dgl.ai/generated/dgl.transform.reverse.html#dgl.transform.reverse) and [update_all](https://docs.dgl.ai/generated/dgl.DGLGraph.update_all.html#dgl.DGLGraph.update_all).

**Comment by sharifza** [comment]
@yzh119

**Comment by yzh119** [comment]
Good idea, I agree that it is potentially important and useful feature.

It's not hard to implement on top of current DGL backend. But we need to discuss the design of interface.

**Comment by yzh119** [comment]
# Proposal

## apply nodes/edges function
There is no need to change as we don't have a reduction phase.

## Message Passing Interface
We need to specify target side for reduce functions, dgl scheduler would use different strategies for different targets, so the changes should be at message-passing interface level instead of inside reduce functions (scheduler should not access the internal of reduce functions).

In [group_apply_edge](https://docs.dgl.ai/generated/dgl.DGLGraph.group_apply_edges.html) function, we provide a `group_by` field which indicates how dgl group edges. Likewise, we can add a `reduce_by` field in our message passing interface, let's take `send_and_recv` as an example:

```python
    def send_and_recv(self,
                      edges,
                      message_func="default",
                      reduce_func="default",
                      apply_node_func="default",
                      inplace=False,
                      reduce_by='dst'):
```

We do not need to worry about message functions as its input (an `EdgeBatch` object) already include information of both source node features and destination nodes features, so it's ok to achieve sent from destination node and received by source node.

Note that there is an `apply_node_func` phase followed the reduce function, `reduce_by='src'` would change the nodes this function applied to.

## Backward Compatiblity
* For built-in functions, we need another `copy_v` function.
* `reduce_by` field is required for both `recv`, `send_and_recv`, `pull`, `push` and `update_all` functions in `DGLGraph` and `DGLHeteroGraph` class.
* We provide `register_*` functions. However, `register_apply_node_func`, `register_reduce_func` behaves differently when we specify different reduce side, and users should be aware of this.

## Other concerns
* @jermainewang mentioned there are some concerns on kernel side, let's discuss it offline.
* @BarclayII , @mufeili , @VoVAllen do have you any suggestions?

**Comment by yzh119** [comment]
@sharifza to conclude this issue.
We have already supported reduce by source node in dgl v0.5.
The `edge_softmax` now have a `norm_by` argument that specifies whether to reduce by source nodes or destination nodes.

For general message passing on graphs, use `g.reverse()` to create a graph with reversed edge directions and apply `update_all` on this reversed graph.
