### ISSUE TITLE
ambiguity on author names (ACM hetero graph dataset)

### ISSUE THREAD

**Issue by shirinmous** [dmlc/dgl#1179]
In ACM hetero graph there are same authors (exact same name) corresponding to three or two nodes in graph?
when i searched these names in dblp, i found that most of them are one author and some are two different authors. 
So this graph is not accurate.

**Comment by BarclayII** [comment]
Thanks for spotting this.  I will add this as a note in the README.

The heterogeneous graph form of ACM is copied from raw data provided by https://github.com/Jhy1993/HAN/tree/master/data/acm, and the problem of duplicate author names does exist.  In particular, I found 434 names that occurred multiple times.

The problem is, since DBLP and ACM are two different datasets, I'm not sure how many names actually points to the same person, rather than different persons having the same name.  For instance, we have four `"D. Sculley"` in the ACM dataset and they are likely to point to the same author.  But there are 7 `"Wei Wang"`'s, which is indeed a quite common Chinese name, and checking how many actually different `"Wei Wang"`'s are in the dataset is hard.  So I just bit the bullet and did not bother cleaning up the dataset.

If you have better ways to de-duplicate the authors, then we are more than happy to incorporate that.

Thanks.
