### ISSUE TITLE
[Feature] provide various data loaders

### ISSUE THREAD

**Issue by zheng-da** [dmlc/dgl#1220]
## 🚀 Feature
DGL should provide data loaders for common data sources, including graph databases, relational databases, no-sql databases, cloud filesystesm, etc. Here are a few examples.
* graph database: Neo4j, Neptune
* relational database: MySQL, PostgreSQL
* no-sql database: HBase
* cloud filesystem: HDFS

## Motivation
If we want DGL to be part of a pipeline in the industry, DGL needs to load data from these common data storage.

**Comment by businessabstraction** [comment]
Please consider loading from Sparql databases as well (Stardog, Neptune if used for RDF, Allegro, etc) Happy to provide more info
Sparql (https://en.wikipedia.org/wiki/SPARQL) is effectively a graph pattern query language. However, RDF databases offer advantage of standard entities and some deterministic deductive reasoning. Some percentage of sites prefer to use Semantic Grpah (Sparql) databases rather than Property Graph databases for integration

**Comment by classicsong** [comment]
> Please consider loading from Sparql databases as well (Stardog, Neptune if used for RDF, Allegro, etc) Happy to provide more info
> Sparql (https://en.wikipedia.org/wiki/SPARQL) is effectively a graph pattern query language. However, RDF databases offer advantage of standard entities and some deterministic deductive reasoning. Some percentage of sites prefer to use Semantic Grpah (Sparql) databases rather than Property Graph databases for integration

Currently, DGL's plan is to support CSV-like data format in its DataLoader first, and provide some stuff to support automatically building the dgl graph. We are not planing to directly support querying the graph database using SPARQL or Gremlin inside DGL. An standalone tool can be used such as https://github.com/awslabs/amazon-neptune-tools/tree/master/neptune-export for Neptune.

**Comment by davidshumway** [comment]
`dgl.data.rdf` appears to be relevant (https://github.com/dmlc/dgl/blob/195f99362d883f8b6d131b70a7868a537e55b786/python/dgl/data/rdf.py)

**Comment by OysterQAQ** [comment]
Is there any progress on this matter?
