### ISSUE TITLE
[RFC] Allow batching DGLHeteroGraph with Zero Nodes/Edges for Some Type

### ISSUE THREAD

**Issue by mufeili** [dmlc/dgl#1261]
## Motivation

Currently we assume that all `DGLHeteroGraph` objects in `dgl.batch_hetero` have the same node and edge types. In practice it is possible that some graphs have only partial node/edge types, in which case batching works more like graph union. 

## Potential Issue

Previously I've discussed this with @jermainewang , who raised a concern that this may make implementations hard to read.

**Comment by jermainewang** [comment]
Let's discuss more about the behavior. Suppose g1 has node type {T1, T2}, and g2 has node type {T2, T3}. According to the proposal, batching g1 and g2 should give a graph of with node types {T1, T2, T3}. As you said, batching should figure out the union set. Then how about the edge types? Suppose g1 has an edge type (T1, E1, T2) while g2 has an edge type (T1, E1, T3). The batched graph would have edge types {(T1, E1, T2), (T1, E1, T3)}.

It this is what we want, the feature could be broken down into three parts.
* A function that finds the union of multiple metagraphs. Question: does networkx support this?
* A function that revises a heterograph by a new metagraph. It will delete graphs of relations not in the new metagraph and add empty graphs of added relations.
* Batching/unbatching should correctly handle relation graphs with no edges.

As for user experience, if the batching API implicitly handles that, then the unbatched graphs could have different metagraphs. But the added relations will have no edges so I don't know how it matters.

Other thoughts?

**Comment by Maybewuss** [comment]
I think batch is different about union. Union is complicated and  needs consider graphs with different metagraphs. But batch should be done between graphs having same metagraph. Besides, dgl can create heterograph with no node or edge instances:`dgl.heterograph({ntype_1, etype, ntype2}:[])`. This graph have metagraph(acnonical_etype):`(ntype_1, etype, ntype2)`.  Since  create opperation support graphs like this, batch opperation should too.

Suppose g1 has g2 have same metagraph while g1 has no nodes or edges. Batching g1 and g2 will not change metagraph. Moreover, g2 has some edge_attributes or node_attributes, should g1 declare these attrbutes sinece it has no noded or edges ? (at least it need to assert like `g1.nodes['ntype_1].data['attr'] = torch.tensor([]) `  because batch function only accept graphs have same attribute name). In this case, Batching g1 and g2 should return a graph retaining g2's attribute. 

Simplify:

- Gragh support  be created with schema(like acnonical_etype) only. But don't support assert attribute name. Workaround is declare like: `g1.nodes['ntype_1].data['attr'] = torch.tensor([]) `
- Graphs to be batched should hava same metapgraph and **same attribute name**. 
- Batch function is not friendly to  graphs lack some instances about ntype or etype.

Moreover:
Shuld creating a graph by schema first, then add instances. This can clearly define the graph structure.
```python
schema = {'ntype': ['n1', 'n2', 'n3'],      
          'etype': [{'src_type': 'n1'
                          'dst_type': 'n3'
                          'name' 'e1' }]} #or just use ('n1', 'e1', 'n3')
g1 = dgl.hetegograph(schema)
instances = {'n1': [0,1,2], # or number of nodes
             'n2': 4,
             'e1': [(0,1),(2,0)]}

g1.add_instances(instances)
```

**Comment by mufeili** [comment]
> Let's discuss more about the behavior. Suppose g1 has node type {T1, T2}, and g2 has node type {T2, T3}. According to the proposal, batching g1 and g2 should give a graph of with node types {T1, T2, T3}. As you said, batching should figure out the union set. Then how about the edge types? Suppose g1 has an edge type (T1, E1, T2) while g2 has an edge type (T1, E1, T3). The batched graph would have edge types {(T1, E1, T2), (T1, E1, T3)}.
> 
> It this is what we want, the feature could be broken down into three parts.
> 
> * A function that finds the union of multiple metagraphs. Question: does networkx support this?

NetworkX has two related operators [`union_all`](https://networkx.github.io/documentation/stable/reference/algorithms/generated/networkx.algorithms.operators.all.union_all.html#networkx.algorithms.operators.all.union_all) and [`disjoint_union_all`](https://networkx.github.io/documentation/stable/reference/algorithms/generated/networkx.algorithms.operators.all.disjoint_union_all.html#networkx.algorithms.operators.all.disjoint_union_all). Unfortunately they cannot fulfill our purposes. `union_all` assumes that the graphs are disjoint, i.e. they cannot have same types while `disjoint_union_all` simply treats all types as distinct. 

> * A function that revises a heterograph by a new metagraph. It will delete graphs of relations not in the new metagraph and add empty graphs of added relations.

Why will we need this function? With the union operation, I presume we will always have a superset with all relations rather than a subset? If this is for unbatching, I suggest constructing new graphs.

> * Batching/unbatching should correctly handle relation graphs with no edges.
> 
> As for user experience, if the batching API implicitly handles that, then the unbatched graphs could have different metagraphs. But the added relations will have no edges so I don't know how it matters.
> 
> Other thoughts?

I suppose we can always check if a graph has nodes/edges of a particular type during unbatching?

**Comment by mufeili** [comment]
@Maybewuss approached me again on this problem, any thoughts? @jermainewang

**Comment by mufeili** [comment]
@Maybewuss See if #1575 addresses your need. In particular, you do not need to set ```g.nodes['ntype_1].data['attr'] = torch.tensor([])``` explicitly.

**Comment by Maybewuss** [comment]
It works now, thanks !
