### ISSUE TITLE
Error: Expected object of backend CUDA but got backend CPU for argument #3 'index' when run pinsage with --use-feature

### ISSUE THREAD

**Issue by yuaneryuaner** [dmlc/dgl#1345]
## To Reproduce

python3 main.py --opt Adam --lr 1e-3 --use-feature

path: dgl/examples/pytorch/recommendation/

## Environment

 - DGL Version (e.g., 1.0):0.4.2
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):pytroch 1.2
 - OS (e.g., Linux):ubuntu16.04
 - How you installed DGL (`conda`, `pip`, source):source
 - Build command you used (if compiling from source):
mkdir build
cd build
cmake -DUSE_CUDA=ON ..
make -j4
 - Python version:3.6.10
 - CUDA/cuDNN version (if applicable):cuda10.0 cudnn7.4.1
 - GPU models and configuration (e.g. V100):1080ti
 - Any other relevant information:
ps. with pandas >0.25, Series.nonzero is not used. Code in examples/pytorch/recommendation/rec/datasets/movielens.py line 93 & 95 should change to Series.to_numpy().nonzero. Or it will cause error

**Comment by BarclayII** [comment]
Hi, as I found multiple issues in the original PinSAGE implementation (speed, correctness, etc.), I have opened a new PR #1334 for refactoring PinSAGE to make it more loyal to the original paper (i.e. it now does similar item recommendation instead of collaborative filtering).  The implementation in `examples/pytorch/recommendation` will then be replaced with the new one.

Thanks.
