### ISSUE TITLE
out of memory question about adptive_sampling example

### ISSUE THREAD

**Issue by xixi-baba** [dmlc/dgl#1361]
## ❓ Questions and Help

I run the example of adaptive_sampling in this link [https://github.com/dmlc/dgl/tree/master/examples/pytorch/adaptive_sampling]
I found the cpu memory usage increase every epoch and the program soon was killed due to the out of memory problem

**Comment by BarclayII** [comment]
Hi,

I cannot reproduce your behavior with the latest master branch or nightly build on Linux.  Could you provide at least the following information?

DGL release version: (0.x.y or from source or nightly)
Operating system: (Linux/Windows/Mac/etc.)

The CUDA version shouldn't matter because adaptive sampling is not implemented with CUDA.

**Comment by xixi-baba** [comment]
Thanks for reply ,
My dgl version is dgl-cuda10.0  0.4 and my operation system is linux，
and all my behavior is to use `python adaptive_sampling.py --batch_size 20 --node_per_layer 40` to run the program and then use `free -h` to check the memory usage, the memory usage increase very fast every epoch

**Comment by BarclayII** [comment]
I see.  We have multiple PRs that tried to fix this issue a couple months ago.  Could you update your installation to preferably the nightly build (or 0.4.2, though I can't remember if 0.4.2 include our fixes) and try again?
