### ISSUE TITLE
Pinsage‘s neighbor sampling method 

### ISSUE THREAD

**Issue by jiazhao2048** [dmlc/dgl#1400]
## ❓ Questions and Help

I notice _bipartite_single_sided_random_walk_with_restart_ method is uesd in the pinsage implementation ( /examples/pytorch/recommendation ) that means the nodes (user or item) aggregate the information from same type of nodes sampled by this method. Is it the intention of Pinsage or just a compromise implementation? 

If it is prior reason, could you share the position of statement in its paper? Thank you! [https://arxiv.org/abs/1806.01973](url)

**Comment by BarclayII** [comment]
The term "random walk" in the section "Importance-based neighborhoods" actually refers to a paper called [Pixie](https://arxiv.org/abs/1711.07601), where the random walk algorithm there actually does a metapath-based random walk with metapath "Pin -> Board -> Pin".  In other words, the successors of a Pin in Pixie random walks are always Pins rather than Boards.  Analogously, the neighbor of an Item in a user-item bipartite graph should be Items rather than Users.

That being said, this is only my anticipation of how PinSAGE works.

**Comment by jiazhao2048** [comment]
Yeah, I check the paper fo Pixie and know how they samples the neighborhoods. There are some tricks or methods are usd in Pixie like Biasing, Multiple Query Pins and even graph pruning. To the best of my knowledge, the training data (positive and negtive pairs) of Pinsage is also generated by Pixie.

So, can we say that if we want to make good use of this dgl pinsage implement, there is some effort to afford like realizing part function of Pixie?

**Comment by BarclayII** [comment]
Right.  The `dgl.bipartite_blahblahblah` function (and in the upcoming release `dgl.random_walk`) is still some distance away from what authentic PinSAGE probably uses.

**Comment by yongari38** [comment]
Does this mean that the forward pass inside DGL Pinsage implementation will only visit item nodes (e.g. movie -> movie -> movie)?
If so, I believe this is wrong.
To my understanding of Pinsage, neighbors of Pins should be Boards, and vice versa. Hence, to migrate Pinsage to Movielens for example, the reasonable approach would be to let:

> nodes (user or item) aggregate the information from ~~same~~ **different** type of nodes.

(i.e., movie -> user -> movie)
