### ISSUE TITLE
How to have an efficient collate fn when the graph is shared by all data points

### ISSUE THREAD

**Issue by chnsh** [dmlc/dgl#1463]
## ❓ Questions and Help

Hi,
In my problem I have a single graph and a data set of N samples with K features.
The way I implement training right now is that I call dgl.batch(graph) in collate fn - but I have the same graph object being copied `batch_size` number of times - is there a way to make this more efficient?

Thanks!

**Comment by jermainewang** [comment]
Hi @chnsh , DGL does not support this unfortunately. In practice, we find duplicating graph structure is not a big problem since most of the memory consumption comes from node/edge features. Please reopen the issue if this does block your model implementation. You could share your scenario and we will take a look. Thanks!

**Comment by chnsh** [comment]
Hi @jermainewang Thanks for replying - the issue is that because of this limitation, I cannot fit larger batches in memory - and that results in a suboptimal result.
Are there any methods to support larger graphs - since dgl.batch becomes 1 large graph
