### ISSUE TITLE
A question about duplicate edges when we retrieve the edge data with the index

### ISSUE THREAD

**Issue by tsotfsk** [dmlc/dgl#1473]
## 📚 Documentation

If a duplicate edge is added to the graph, it will make an error to retrieve the edge data with the index
`self.g.edges[self.click_user_vertices, self.click_item_vertices].data.update(edge_data)`

the shape of the self.click_user_vertice and self.click_item_vertices is 60W
but it told me that the shape of the edge data is 67W+ 
If I don't add duplicate edges，no this problem.

**Comment by VoVAllen** [comment]
Hi,

This is expected. Each edge has an independent row, even if it is duplicate with other edges (has same source and destination node). Therefore `self.g.edges[self.click_user_vertices, self.click_item_vertices]` would return more than 60W edges, since there's duplicate edges. 

Feel free to ask if you have any other confusions or tell us what's your expected result.
