### ISSUE TITLE
Problems encountered when updating the features of edges

### ISSUE THREAD

**Issue by mliwang** [dmlc/dgl#1518]
## ❓ Questions and Help
I encountered a strange and crazy question, seeking answers.

 print("self.rating_user_vertices",len(self.rating_user_vertices))
#Output:self.rating_user_vertices 408065
print("self.rating_item_vertices",len(self.rating_item_vertices))
#Output:self.rating_item_vertices 408065
print("update data size:",prior_tensor.size())
#Output:update data size: torch.Size([408065])
self.g.edges[self.rating_user_vertices, self.rating_item_vertices].data['prior']=prior_tensor
#DGLError: Expect number of features to match number of edges. Got 408065 and 1151661 instead.

I can't understand why this problem occurs. This problem also occurs when using a smaller part of the data, but it does not exist when I try the official demo.

**Comment by VoVAllen** [comment]
probably there's duplicate edges in your dataset. The number of `g.edges()` should match the first dim of the prior_tensor

**Comment by BarclayII** [comment]
The first part of the claim from @VoVAllen was correct.  For instance, if you have duplicate edges:
```python
users = torch.LongTensor([0, 1, 2, 0])
items = torch.LongTensor([1, 2, 3, 1])
g = dgl.graph((users, items))
```

Your `users` and `items` have two (0, 1) entries.  If you run it with `g.edge_ids(users, items)`, DGL cannot know which concrete edge your (0, 1) entry correspond to.  So it will instead return both edges for every occurrence of (0, 1), resulting in returning 6 edge IDs:

```
>>> g.edge_ids(users, items, return_uv=True)
(tensor([0, 0, 1, 2, 0, 0]),
 tensor([1, 1, 2, 3, 1, 1]),
 tensor([0, 3, 1, 2, 0, 3]))
```

Similarly, if you run `g.edges[users, items].data` you will get 6 rows:
```
>>> g.edges[users, items]
EdgeSpace(data={'x': tensor([[-0.1144, -0.5004,  1.4033,  0.5975,  0.2690,  0.4656],
        [ 0.4013,  0.0530, -0.0538,  0.1103,  0.6431, -1.0944],
        [-2.1310,  0.7737, -1.0692, -0.9439,  0.7078, -0.3491],
        [-0.7267, -0.5973,  0.5847,  1.3025, -0.1505,  0.5238],
        [-0.1144, -0.5004,  1.4033,  0.5975,  0.2690,  0.4656],
        [ 0.4013,  0.0530, -0.0538,  0.1103,  0.6431, -1.0944]])})
```

The solution to that is to simply use edge IDs instead of the syntax `g.edges[users, items]`.  For instance, in your case you can simply use `g.edata['x']` to access the edge features on all edges, or `g.edata['x'][2]` for accessing the third edge's feature.

**Comment by BarclayII** [comment]
Please feel free to reopen if the problem is not addressed.
