### ISSUE TITLE
PinSAGE Multi-GPU

### ISSUE THREAD

**Issue by trinayan** [dmlc/dgl#2159]
Hi,

I am looking on some guidance on developing a multi-GPU version of PinSAGE. I know DistributedDataParallel is the recommended way. Typically when training using DDP, we define a train sampler built from a DistributedDataSampler that ensures that each GPU works on unique data. However PinSAGE has its own sampler function and I am confused on how to integrate a sampler to split the data across multiple GPUs with that.  If anyone could give some high-level hints it would be really helpful. Thank you.

**Comment by BarclayII** [comment]
In our example, the loss function is measuring whether two items are co-purchased by the same user.  The positive examples and negative examples are actually computed on-the-fly instead of by iterating over all possible item pairs.  The reason is that we simply have too many positive item pairs to even fit them into memory.  Given that, I think it should be OK not to ensure each worker operating on unique data.

**Comment by trinayan** [comment]
got it. thanks
