### ISSUE TITLE
Cannot build DGL from the source code.

### ISSUE THREAD

**Issue by khaled-rahman** [dmlc/dgl#2162]
I followed the steps to build DGL
```
# mkdir build && cd build
# cmake ..
# make
```
I tried to build the DGL from source code but it shows errors like the following:
```
dmlc-core/include/dmlc/./serializer.h:63:27: error: ‘Write’ is not a member of ‘dmlc::serializer::UndefinedSerializerFor<bool>’
     Else::Write(strm, data);
                           ^
```
What could be the possible reason for this? Any idea?

**Comment by classicsong** [comment]
I think you need to follow the instructions here: https://docs.dgl.ai/en/0.5.x/install/index.html#install-from-source

**Comment by VoVAllen** [comment]
It's wired. Did you initialize the submoudule properly? And which compiler(gcc or llvm) and os(ubuntu, centos, etc.) are you using?

**Comment by khaled-rahman** [comment]
Yes, I initialized submodules properly. I used GCC 4.8 on a server machine with RedHat os. I have been able to build all third-party modules successfully. For example, I built a dmlc-core without any problem. However, when I was trying to build the DGL, it was throwing these error messages. It would be very helpful to know what is happening here. Is it related to the little-endian or big-endian problem? If yes, how can I build it.

**Comment by VoVAllen** [comment]
Hi,

We need GCC>=5 now for building DGL. You could refer to [this](https://github.com/hcho3/centos7-with-devtoolset-4/blob/mainline/Dockerfile) to install the devtoolset-4 to get gcc 5

**Comment by khaled-rahman** [comment]
Hi @VoVAllen, thank you so much. It worked! I loaded the higher gcc version using `module load gcc/9.2.0` and it worked fine.

**Comment by hv0905** [comment]
Hi @khaled-rahman , I've just tried to build DGL v1.1.2 using gcc version `11.4.0` on a `s390x` (IBM Z) architecture machine, and the same error encountered:  
![image](https://github.com/dmlc/dgl/assets/29349119/16a194da-dc60-4099-ad82-dcd4948e6be7)  

Are there any other options you adjusted to solve the problem instead of upgrading the compiler? Any help would be thanked!

My compiler version:
![image](https://github.com/dmlc/dgl/assets/29349119/7e2cba8b-de37-4653-a004-7ba37aecd568)
