### ISSUE TITLE
ValueError: Expect graph 0 and 31 to have the same node attributes when node_attrs=ALL

### ISSUE THREAD

**Issue by niraj-bhujel** [dmlc/dgl#2211]
## ❓ Questions and Help

Hi, dgl team, I frequently got this error 

>    for iter, (obsv_graph, target_graph) in enumerate(dataloader):
  File "/home/dl-asoro/.local/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 560, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/dl-asoro/Desktop/Message_GCNN/utils.py", line 201, in collate
    return dgl.batch(obsv_graphs), dgl.batch(target_graphs)
  File "/home/dl-asoro/.local/lib/python3.5/site-packages/dgl/graph.py", line 4177, in batch
    node_attrs = _init_attrs(node_attrs, 'node')
  File "/home/dl-asoro/.local/lib/python3.5/site-packages/dgl/graph.py", line 4167, in _init_attrs
    .format(ref_g_index, i, mode, attrs, g_attrs))
**ValueError: Expect graph 0 and 31 to have the same node attributes when node_attrs=ALL, got {'pos', 'vel', 'frames'} and {'Eh', 'pos', 'vel', 'frames', 'h', 'Bh', 'Dh', 'Ah'}.**

I am using 0.4.3post2. The error occur in second epoch. The node attributes `'Eh', 'h', 'Bh', 'Dh', 'Ah'` are added in the forward path while `'pos', 'vel', 'frames' `  are added during the graph creation.   Can I get some help, about this error? Thanks in advance and let me know what kind of information is required?

**Comment by mufeili** [comment]
As the error message suggests, with `node_attrs=ALL`, `dgl.batch` expects all graphs to have same node features and tries to merge them in batching graphs. It turns out that graph 0 and 31 have different node features, {'pos', 'vel', 'frames'} for graph 0 and {'Eh', 'pos', 'vel', 'frames', 'h', 'Bh', 'Dh', 'Ah'} for graph 31. If your model processes all graphs in a batch simultaneously, it should add `'Eh', 'h', 'Bh', 'Dh', 'Ah'` for all graphs in the forward path. That says, one of the following cases happens:

* Your model failed to add node features `'Eh', 'h', 'Bh', 'Dh', 'Ah'` for some graphs. In that case, you want to check if there are corner cases your model failed to handle.
* It is not intended for your model to add these node features for all graphs simultaneously. In that case, either it was not the right place that you invoked `dgl.batch` or you should use `dgl.batch(..., node_attrs=['pos', 'vel', 'frames'])` instead.

**Comment by niraj-bhujel** [comment]
Thanks you the quick response. `dgl.batch(..., node_attrs=['pos', 'vel', 'frames'])` fix the problem. But the performance is slightly lower. Do you have any idea how the model failed to add node features for some graphs?

**Comment by mufeili** [comment]
> Thanks you the quick response. `dgl.batch(..., node_attrs=['pos', 'vel', 'frames'])` fix the problem. But the performance is slightly lower. Do you have any idea how the model failed to add node features for some graphs?

You need to check the place where your model is supposed to add these features and understand why the feature addition failed.
