### ISSUE TITLE
[Bug?] RGCN Multi-GPU example crashes on OGBN-MAG if PyG is installed

### ISSUE THREAD

**Issue by BarclayII** [dmlc/dgl#2327]
## To Reproduce

Run
```
python examples/pytorch/rgcn/entity_classify_mp.py --gpu 0,1 -d ogbn-mag
```
with PyG installed.  It crashes with `Cannot re-initialize CUDA in forked subprocess` error.

## Expected behavior

It should not crash.

## Environment

 - DGL Version (e.g., 1.0): master
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 1.6.0
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source): source
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version (if applicable): CUDA 10.1
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

## Additional context

Not even sure where I should report this issue so I'm just bookkeeping it here just in case some other people is helplessly scratching their head.

**Comment by classicsong** [comment]
OGB dataloader prefer to load data in PyG format other than DGL.

**Comment by nv-dlasalle** [comment]
This seems to be true for all OGB datasets, and the cause looks to be that the pytorch geometric loading code initializes a cuda context when imported, and since ogb.nodeproppred initializes both DGL and PyG loaders in `__init__.py`, the root process initializes a cuda context. Using fork() after doing invokes undefined behavior.

This means if PyG and DGL are installed, we need to use the spawn method for multi-process runs, to avoid this. It may be worth working with the OGB folks to refactor https://github.com/snap-stanford/ogb/blob/master/ogb/nodeproppred/__init__.py in order to allow only import the DGL loader.
