### ISSUE TITLE
is homogeneouse block possible?

### ISSUE THREAD

**Issue by patricxu** [dmlc/dgl#2520]
It seems that any homogeneouse graph will be converted to hetrogeneouse block. Is this really necessary when the raw graph is homogeneouse?  If not so, how can I get a cleaning homogenenouse block?

**Comment by BarclayII** [comment]
The block has to be homogeneous because for a single GNN layer the number of input nodes and the number of output nodes is different.  For instance, to compute the output of one node you may need more than one nodes' input.  Such computation dependency is best described as a bipartite graph (which is heterogeneous).

Please feel free to follow up.  Thanks!

**Comment by patricxu** [comment]
Bipartite graph! That's exactly what I mean heterogeneous. I found the following way to convert to homogeneouse graph. 

`        src, dst = graph.all_edges()
        homoG = dgl.graph((src, dst), num_nodes=graph.number_of_nodes())`

But there are some unexpected results in terms of block. I will start an another thread. Thanks!
