### ISSUE TITLE
When an ntype or etype is empty in every input graph, dgl.batch() erases their data frames in the output

### ISSUE THREAD

**Issue by noncomputable** [dmlc/dgl#2526]
## 🐛 Bug

If there are no nodes or edges of a particular ntype or etype in any of the input graphs, dgl.batch() erases their data frames in the output batch.

## To Reproduce

Take graphs g1 and g2 with a node feature x for ntype t. Batch them with `b = dgl.batch([g1, g2])`. Later computations access `b.nodes["t"].data["x"]`, expecting it to exist, even if empty. However, sometimes each graph in the input happens to have no nodes of ntype t. When this happens, `b.nodes["t"].data["x"]` will not exist and it will raise a KeyError. The same happens with edges and edge features.  

## Expected behavior

Even if there are no nodes or edges of that ntype or etype containing that feature in the input graphs, the output batch should have the same features as the input graphs.

## Environment

 - DGL Version (e.g., 1.0): 0.5.3
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 1.6.0
 - How you installed DGL (`conda`, `pip`, source): conda
 - Python version: 3.7

**Comment by jermainewang** [comment]
Hi @noncomputable , thanks for the report and the proposed fix. Instead of adding an option to the API, I'd like to see whether it's possible to extend the current semantic a little bit to make it more convenient. Essentially, we have the following situations:

1. Batching a list of graphs and none of them are empty. In this case, DGL requires them to have the same feature schema.
2. Batching a list of graphs but some of them are empty. Currently, DGL requires non-empty graphs to have the same feature schema but not empty graphs. Empty graphs are ignored during batching.
3. Batching a list of empty graphs. Currently, DGL will produce an empty graph with no feature at all.

I think we want to keep the semantics for scenario 1 and 2. For 3, the proposal is to apply the same logic as in scenario 1, i.e., all empty graphs must have the same schema and the result will inherit it. Does that sound right to you?

If so, then the fix will be replacing the logic here https://github.com/dmlc/dgl/blob/54f186bba0bd3ec6bce588e5844e130119398e1c/python/dgl/batch.py#L194-L196 by including all the frames if the input is a list of empty graphs.

**Comment by noncomputable** [comment]
I went with extending the params because it would avoid breaking any code that assumes features won't exist after batching, e.g. to check whether data needs to be added. But I'm comfortable with your proposal too, if you think it's safe.

We can change your snippet to
`all_empty = all(g._graph.number_of_nodes(ntype_id) == 0 for g in graphs)` 
`frames = [ 
     g._node_frames[ntype_id] for g in graphs 
     if g._graph.number_of_nodes(ntype_id) > 0 or all_empty ]`
and do the same for edges.

**Comment by noncomputable** [comment]
I found another, related issue https://github.com/dmlc/dgl/issues/2528.

I would be surprised if many people working on generative models in DGL haven't run into the issues with empty graphs and incorporated lots of workarounds that rely on this unexpected behavior.

**Comment by noncomputable** [comment]
I found another, related issue #2528.

**Comment by noncomputable** [comment]
There is actually a significant roadblock in using this feature usefully: there is no way to specify the shape of the data in an empty graph. The only way to set the feature is `g.ndata["h"] = torch.tensor([])`, but this necessarily assigns shape=() to the feature. There should be a way to specify the feature shape without having to add feature data. Here's a proposal: https://github.com/dmlc/dgl/issues/2535

**Comment by jermainewang** [comment]
> I went with extending the params because it would avoid breaking any code that assumes features won't exist after batching, e.g. to check whether data needs to be added. But I'm comfortable with your proposal too, if you think it's safe.
> 
> We can change your snippet to
> `all_empty = all(g._graph.number_of_nodes(ntype_id) == 0 for g in graphs)`
> `frames = [ g._node_frames[ntype_id] for g in graphs if g._graph.number_of_nodes(ntype_id) > 0 or all_empty ]`
> and do the same for edges.

The change looks good to me. Would you mind changing your PR accordingly? Many thanks!

**Comment by noncomputable** [comment]
Done!
