### ISSUE TITLE
The gap between tutorials and examples

### ISSUE THREAD

**Issue by vpegasus** [dmlc/dgl#2653]
## 📚 Documentation

Thanks for sharing such a great project, and I'm learning on DGL. The tutorials for learning can be a clear and easy road map, great! However, I find there may be a bit of gap between tutorials and their related examples. 

For example, I learnt to how to do link prediction for heteograph by using DGL, and the related examples are RGCN, when I dig into the source code in this folder: https://github.com/dmlc/dgl/tree/master/examples/pytorch/rgcn,
the model and the training way are very different from those in tutorials from a green-hand ( me :< ) eye, which confuse me.

Along with the example, I also dig into the source code for  `dgl.data.knowledge_graph` and in method `build_knowledge_graph`, As kg datasets are usually heteographs, 'Create a DGL Homogeneous graph with heterograph info stored as node or edge features. ' as commented, which confuse me deeply. It may make sense taking others like efficiency into consideration, but i got no such interpretation. Such homographs are still passed to RGCN a hetero model, and I can't grasp the insight idea.

Above confusion is just an example when learning with tutorials and their related examples. 
by the way, I also have no idea about the relationship between a graph and a dataset, as when sampling, a graph (without convert to a dataset class) is OK for dataloader.
I have been learning on DGL a few weeks, please give me some guidance to make this progress less painful,
thanks in advance!!!

**Comment by yzh119** [comment]
Hi @vpegasus , thanks for your feedback and I do think your concern is correct.

The rgcn folder you were browsing regard the heterograph as a homogeneous graph, which is against the way we instructed user to do in the tutorial. Please read the code in another folder [rgcn-hetero](https://github.com/dmlc/dgl/tree/master/examples/pytorch/rgcn-hetero), which might be more concise. Sorry about the confusion because heterograph is not supported before DGL 0.4 and regarding heterograph as homogeneous graph is the only way we write rgcn before the landing of heterograph support.

What do we mean by `Create a DGL Homogeneous graph with heterograph info stored as node or edge features. ` is: we merge all graphs corresponding to different types as a unified graph, and the "types" information are attributed as edge/node features.

btw, feel free to join our [slack channel](https://join.slack.com/t/deep-graph-library/shared_invite/zt-eb4ict1g-xcg3PhZAFAB8p6dtKuP6xQ) where our users/developers could address your concerns.

**Comment by vpegasus** [comment]
@yzh119  thanks for your reply and your reply help me very much

**Comment by bosskwei** [comment]
Hi guys, the rgcn really confused me a lot until I read this issue, is that means example/rgcn with RelGraphConv is a legacy and walk around implementation? so the HeteroGraphConv can do everything (R-GCN, R-GAT, R-SAGE) and depracate RelGraphConv?
