### ISSUE TITLE
SAGEConv potentially has a minor bug with regards to the neighborhood aggregation

### ISSUE THREAD

**Issue by drsealks** [dmlc/dgl#2719]
According to the original SAGEConv paper, we aggregate the embedding of surrounding nodes. We then add the transformed representation of the node itself, see this line here:

https://github.com/dmlc/dgl/blob/7380d61eb97d541ce92d0a7b578b0e5b571eb0c0/python/dgl/nn/pytorch/conv/sageconv.py#L234

It seems like that a node can't reach any other nodes, it's representation should just be calculated based on its own transformation matrix, i.e.

`rst = self.fc_self(h_self)`

However, this is not the case in the current implementation. What happens is that if there not nodes around, a fake node with a zeroed embedding is created. It is then passed through a linear layer, which happens to have a non-zero bias and while the product of a zero vector and the matrix gives zeros, the aggregated signal from that fake neighbour appears to be non-zero due to biases. 

By doing that, we seem to be creating unwanted signal change on a node, which seems to be conceptually wrong. 

Do you think this is a problem is by design? If this is a problem, please let me know, I will submit a PR. 

Thanks!

**Comment by BarclayII** [comment]
I see what you mean.  For isolated nodes the latter term `self.fc_neigh` would incur a (learnable) bias.

I agree with your reasoning.  Our implementation though is based on the original GraphSAGE implementation, which [seems to also adds a learnable bias to the result even if the node is isolated](https://github.com/williamleif/GraphSAGE/blob/master/graphsage/aggregators.py#L61-L62).  So I guess the problem is not significant.
