### ISSUE TITLE
[Bug?] strange behivior of bipartite_from_networkx() 

### ISSUE THREAD

**Issue by e-yi** [dmlc/dgl#2808]
## To Reproduce

Step1:
```python
import networkx as nx
import dgl

B = nx.DiGraph()
B.add_nodes_from([1, 2, 3, 4], bipartite=0, some_attr=th.Tensor([1,2,3,4]))
B.add_nodes_from(["a", "b", "c"], bipartite=1)
B.add_edges_from([(1, "a"), (1, "b"), (2, "b"), (2, "c"), (3, "c"), (4, "a")])
```

Step2:
```python

choice = 0 # 0,1,2,3

g = { 0: dgl.bipartite_from_networkx(B,'A','e','B'),
      1: dgl.bipartite_from_networkx(B,'B','e','A'),
      2: dgl.bipartite_from_networkx(B,'A','e','B',u_attrs=['some_attr']),
      3: dgl.bipartite_from_networkx(B,'B','e','A',u_attrs=['some_attr'])
    }[choice]
```

Step3:
run `dgl.batch((g,g,g))`

And when `choice` is 1 or 3, it throws DGL Error. 

## Expected behavior

All 4 choices should produce no error?

## Environment

 - DGL Version (e.g., 1.0): '0.6.0post1'
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):  '1.8.1'
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): 
 - Python version: 3.7.10
 - CUDA/cuDNN version (if applicable): 11
 - GPU models and configuration (e.g. V100): 
 - Any other relevant information:

**Comment by ab-10** [comment]
The error occurs due to lines 171 and 173 in [batch.py](https://github.com/dmlc/dgl/blob/master/python/dgl/batch.py#L171), where nodes and edges are sorted:
```
171: relations = list(sorted(graphs[0].canonical_etypes))
172: relation_ids = [graphs[0].get_etype_id(r) for r in relations]
173: ntypes = list(sorted(graphs[0].ntypes))
```
Removing `sorted` fixes the issue. As far as I understand sorting was performed as part of an optimization, could @VoVAllen or @yzh119 please explain the rationale behind sorting here as I'm new to the codebase myself.

If it is fine to remove sorting, I'm happy to do so and submit a PR.
