### ISSUE TITLE
about adajacency matrix A

### ISSUE THREAD

**Issue by DMW123** [dmlc/dgl#2846]
## ❓ Questions and Help

Hi! Thank you for your great work.I have a question about the adajacency matrix A.I don't see that A is used in source code(during forward and infenence). This is differernt from the idea of  section 3.3(Issues of training deeper GCNs) of your paper. And why? Thank you!

**Comment by jermainewang** [comment]
The `DGLGraph` object stores the graph adjacency in an C-mapped object called GraphIndex, which you could view it the equivalence of the adjacency matrix A. For message passing operators like `update_all`, they will directly access the internal data structure of GraphIndex instead of working on backend sparse tensor for efficiency reason. If you are interested, you could see [here](https://github.com/dmlc/dgl/blob/master/python/dgl/backend/pytorch/sparse.py#L83) on how gspmm is implemented as an operator on graph index and tensors.

**Comment by DMW123** [comment]
Thank you for your reply. I have understood about this problem. thanks again.

**Comment by DMW123** [comment]
Thank you for your reply. I have understood about this problem. thanks again.

> The `DGLGraph` object stores the graph adjacency in an C-mapped object called GraphIndex, which you could view it the equivalence of the adjacency matrix A. For message passing operators like `update_all`, they will directly access the internal data structure of GraphIndex instead of working on backend sparse tensor for efficiency reason. If you are interested, you could see [here](https://github.com/dmlc/dgl/blob/master/python/dgl/backend/pytorch/sparse.py#L83) on how gspmm is implemented as an operator on graph index and tensors.

# Thank you for your reply. I have understood about this problem. thanks again.
