### ISSUE TITLE
[RFC] add the `exclude_edges` argument in `sample_neighbors`

### ISSUE THREAD

**Issue by zheng-da** [dmlc/dgl#2944]
In link prediction tasks, we sample a set of edges, compute the embeddings of the endpoint nodes of the edges and compute the node similarity to predict the existence of edges. It is possible that the edges to be predicted are also used to compute node embeddings with message passing, which causes information leak and potentially decreases the model performance. 

Thus, we propose the extension of `sample_neighbors` by adding a new argument called `exclude_edges`. The interface of the extended `sample_neighbors` is:
```
dgl.sampling.sample_neighbors(g, nodes, fanout, edge_dir='in', prob=None, replace=False, copy_ndata=True,
                                                       copy_edata=True, _dist_training=False, exclude_edges=None)
```
The argument has a value of an edge ID array. By default, its value is `None`. If we want to exclude certain edges in the neighbor sampling for the seed nodes, we should pass a 1D array that contains the edge IDs.

**Comment by zheng-da** [comment]
@jennyzhang0215 can you provide your opinions on this proposal here?

**Comment by jennyzhang0215** [comment]
*exclude_edges* as a 1D array can meet many cases.  A more complicated situation is that for different seed nodes the edges to be excluded are different. In this case, *exclude_edges* should be in the format of a list of lists. Each list corresponds to a seed node in the *nodes*.

**Comment by jennyzhang0215** [comment]
If the *exclude_edges* is a 1D array, it means that all the seed nodes exclude the same set of edges when sampling neighbors. So what if different seed nodes need to exclude different sets of edges? For example, seed node *n1* needs to exclude edge *e1* and node *n2* needs to exclude *e2* and *e3*. In this case, if *nodes=[n1, n2]*, then * exclude_edges* can be *[[e1], [e2,e3]]*, which is a list of lists. (We cannot use a 2D tensor here, because the number of edges to be excluded is different.)

However, I cannot show a good application for the above case. So we can just regard *exclude_edges* as a 1D array (for homograph) and a dict (for heterograph) at the current stage.
