### ISSUE TITLE
Load graph batches from disk

### ISSUE THREAD

**Issue by theisjendal** [dmlc/dgl#2979]
## 🚀 Feature

Option to load graph from disk, such that it is not necessary to have the complete graph loaded in memory all at once. One option would be to overload the a dataloader such that the graph was instead a path to a graph/

## Motivation
When working with large graphs, having them in memory is infeasible. It can therefore be difficult to utilise this great library when the graph size increases a lot.  

## Alternatives
I'm not sure if it is possible, but the distributed dgl network may be usable in this scenario. 

## Pitch
I want the option to load subgraphs into memory and train on them without having the whole graph in memory. It would be similar to pytorch's get item in their dataloader.

**Comment by VoVAllen** [comment]
Hi,

It's hard to support this without algorithm change, because reading from disk is far slower than reading from memory. However, I would suggest taking a look on the clusterGCN example https://github.com/dmlc/dgl/tree/master/examples/pytorch/cluster_gcn. It only uses part of graph at each batch, and swap another after several batches

**Comment by theisjendal** [comment]
Hi,

I'll look into it, otherwise I'll downscale the graph, e.g., limiting the in/out degree or similar, but thanks for the quick response :)
