### ISSUE TITLE
#edge is not matched and some API bugs

### ISSUE THREAD

**Issue by StrongWeiUMN** [dmlc/dgl#3144]
## 📚 Documentation

I recently looked at some dataset APIs provided by the DGL, and I found some bugs. For example, 
<br>

```python
pip install dgl
dataset = dgl.data.AmazonCoBuyComputerDataset()
graph = dataset[0]
```
#edge of the Amazon Co-Purchase dataset is not matched with the document. I think it may be due to the .to_bidirect function (i.e., DGL adds the reverse edges and removes the duplicates)
<br>

```python
dataset = dgl.data.CoauthorCSDataset()
graph = dataset[0]
```
#edge of the Coauthor dataset is not matched with the document.
<br>

```python
dataset = dgl.data.rdf.AIFBDataset()
```
Error: No module named 'rdflib'
<br>

```python
dataset = dgl.data.FraudDataset('yelp')
```
Error: module 'dgl.data' has no attribute 'FraudDataset'
<br>

Therefore, I wonder if the DGL team can check all of the provided dataset APIs and update the documents in the future. Thanks!

**Comment by jermainewang** [comment]
Hi @StrongWeiUMN , thanks for reporting the issue. For the problem that the number of edges in the docstring does not match the docstring, it is indeed caused by the preprocessing step as you have correctly suspected. I would like to take this chance to hear some feedback on this topic. For example,
* Which statistic is more important to you? The raw number of edges or the number of edges after preprocessing?
* What do you think of the current default way of preprocessing graph (i.e., removing duplicated edges and adding reverse edges)? Is it desired?

For the other issues, @HuXiangkun would you mind having a look at them?

**Comment by HuXiangkun** [comment]
Hi @StrongWeiUMN , thank you for pointing out this issue. I have gone through all the dataset APIs, and fix the doc string problem. 

For `dgl.data.rdf.AIFBDataset()`, you need to install rdflib. 

For the error in `dgl.data.FraudDataset('yelp')`, I didn't reproduce it in the latest version of DGL. Can you provide the details of your environment? Thanks!

**Comment by StrongWeiUMN** [comment]
Hi @jermainewang, thanks for replying. I think the current data pre-processing is good for me and satisfied my requirements. 

The only thing that confused me before is why the document doesn't match the graph API returns. Now, it makes sense. So, I think it will be more friendly to the users if the DGL team can add a couple of sentences about how the API pre-processed the data and the change of the dataset (just like the CoraFull).

@HuXiangkun It is my bad. I ran the script on the Google Colab with `!pip install dgl`, it installs the stable version 0.6.x, while I use the latest version 0.7.x tutorial. Once I turn to install the nightly build version, it works out.   

Thank you all a lot!
