### ISSUE TITLE
Node/EdgeDataLoader return blocks with no features when DistGraph is used

### ISSUE THREAD

**Issue by jwyyy** [dmlc/dgl#3278]
## 🚀 Feature

In Node/EdgeDataLoader, if DistGraph is used, the blocks generated by a dataloader don't have graph features. 

## Motivation

Currently, returning blocks with features is supported for DGLGraph. Node/EdgeDataLoader is expected to return the same set of outputs no matter which graph mode is used, either DistGraph or DGLGraph. 

## Alternatives

One alternative is to manually copy features to blocks returned by Node/EdgeDataLoader, like this [example](https://docs.dgl.ai/en/latest/api/python/dgl.distributed.html) in DistDataLoader. 

## Pitch

It is a good idea to unify the behaviors of Node/EdgeDataLoader, making models and data pipelines free of input graph mode.

**Comment by jwyyy** [comment]
I have created a PR https://github.com/dmlc/dgl/pull/3279 for this issue.

**Comment by jermainewang** [comment]
Hi @jwyyy , thanks for the proposal. One concern however is the copy overhead. Since the node/edge data will likely be stored remotely, fetching data via network will be quite slow. For DGLGraph, we adopt a strategy called lazy copy -- the returned block graph holds a reference to the parent features and the copy only happens when users access the data via `ndata` or `edata` (see https://github.com/dmlc/dgl/blob/master/python/dgl/frame.py#L110-L129). I suggest use a similar implementation for distributed data loader.

**Comment by jwyyy** [comment]
Hi @jermainewang, thank you for your feedback! I want to confirm it with you before I continue the implementation: you meant that when a DistGraph is used in Node/EdgeDataLoader, we only keep the reference to its feature DistTensor instead of doing the actual copy (what I did in the old PR). Copying only happens when blocks are computed inside a model.

**Comment by jermainewang** [comment]
> Copying only happens when blocks are computed inside a model

To be more accurate, copy only happens when user accesses its ndata/edata (e.g., `block_graph.srcdata['h']` will trigger the copy of the `'h'` feature but not the others).

**Comment by jermainewang** [comment]
Hi @jwyyy , sorry for the late reply as I was thinking of what are the minimal way to realize it. Since the request is motivated from distributed graph sampling, where the parent graph is a `DistGraph` while the sampled subgraph (or block graph) is a `DGLGraph`. I think modifying `DGLGraph`'s component may be easier. Specifically, I am thinking of handling it in the [`Column` class](https://github.com/dmlc/dgl/blob/master/python/dgl/frame.py#L80). To briefly describe the data structure, each `DGLGraph` contains two `Frame`s for holding node and edge features resp., which you could view as dictionaries from feature names to feature tensors, called a `Column`. Each `Column` stores features of all nodes/edges batched on the first dimension in one tensor.

When a subgraph is created (e.g., from neighbor sampling or to_block), instead of extracting sub-features, the columns of the subgraph holds a pointer to the parent graph's column and also an index array. The feature slicing happens whenever a user tries to access the feature data via `DGLGraph.ndata` or `DGLGraph.edata`, which will eventually calls `Column.data` to get the feature tensor. Please see the [implementation](https://github.com/dmlc/dgl/blob/8e525dad71c0857dd93d8ed5eaa7aa57516acbc0/python/dgl/frame.py#L140-L161) for more details.

What I am thinking of, is, whenever a subgraph (a DGLGraph) is sampled from a `DistGraph`, the Column will also hold a reference to the `DistTensor` object which stores the node/edge features of a `DistGraph`. Holding a `DistTensor` object does not incur any memory copy. Afterwards, when a user accesses the feature data which eventually calls `Column.data`, it invokes [`DistTensor.__getitem__`](https://github.com/dmlc/dgl/blob/8e525dad71c0857dd93d8ed5eaa7aa57516acbc0/python/dgl/distributed/dist_tensor.py#L167-L170) to pull data from the remote server and store it locally. In this way, the copy is lazily performed and is on-demand.

**Comment by jwyyy** [comment]
Hi @jermainewang , thank you very much for your clear and careful explanation! I have read the related scripts and made a new implementation plan based on your suggestion. I tried to keep the core components intact, but it seems modifying `Column` class is a good solution to avoid further complications. Will make/update the PR once I am done. (Also, please ignore yesterday's PR. It was a sub-optimal solution.)

**Comment by jwyyy** [comment]
Hi @jermainewang , I have made a new PR https://github.com/dmlc/dgl/pull/3323 using the implementation that we discussed above. (I can close the old PR.) The new PR was okay in all tests except MXNet CPU unit test which seems to be a network connection error:
```
=========================== short test summary info ============================
FAILED tests/compute/test_data.py::test_reddit - requests.exceptions.ChunkedE...
===== 1 failed, 2237 passed, 34 skipped, 717 warnings in 774.21s (0:12:54) =====
````

The current implementation doesn't have a test on checking features copied from DistGraph. Since I had trouble with directly copying features from DistGraph within a reasonable amount of time, I would like to know what a good test should look like, especially how large a DistGraph should be used and how long the test should be. Would you mind providing more details on writing test cases? I will re-run the Jenkins test with new-added test cases.

Regarding the actual implementation, the major change of `Column` is to allow passing `DistTensor` with node/edge IDs sampled in blocks. `DistTensor` and the ID tensor are taken as a tuple ([L187](https://github.com/dmlc/dgl/pull/3323/files#diff-3de6dd42cee69530727f0bbf83cd0cbe6ed34798d683210fdac23ace5a6a2e8aR187)). The ID tensor is assigned to `index` which can be further sliced by `_LazyIndex`. The actual retrieval of torch from DistTensor will happen when [`data`](https://github.com/dmlc/dgl/pull/3323/files#diff-3de6dd42cee69530727f0bbf83cd0cbe6ed34798d683210fdac23ace5a6a2e8aR161) is used to access `data` property and [`to()`](https://github.com/dmlc/dgl/pull/3323/files#diff-3de6dd42cee69530727f0bbf83cd0cbe6ed34798d683210fdac23ace5a6a2e8aR217) is called to copy features to device. Due to the new input format tuple `(DistTensor, tensor)`, some checks in `Frame` and `DGLHeteroGraph` are conducted to allow this data tuple to be passed to `Column` safely.

When you have some time to read the code, please let me know your feedback. I really appreciate your time and suggestions. Thanks a lot!
