### ISSUE TITLE
results error when using dgl.broadcast_nodes

### ISSUE THREAD

**Issue by ChenChenGith** [dmlc/dgl#3349]
## To Reproduce

I test the example in the docs: 
![image](https://user-images.githubusercontent.com/45627234/133062126-6e16dccd-1bfe-42b6-a755-e52a53df7121.png)

Here are my output:
![image](https://user-images.githubusercontent.com/45627234/133061930-d057e52a-a4fa-4d61-867f-6efb33aec692.png)

the output shape should be (2,5), but now it's (1, 10)
## Environment

 - DGL Version (e.g., 1.0): 0.6.1
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): torch 1.9.0
 - OS (e.g., Linux): win
 - How you installed DGL (`conda`, `pip`, source):  pip install
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version (if applicable): no cuda
 - GPU models and configuration (e.g. V100): 
 - Any other relevant information:

**Comment by jwyyy** [comment]
It seems the problem is: `feat[0]` is a 1-d tensor, and using `torch.repeat_interleave()` only extend it horizontally. Please see these two references: [dgl.broadcast_nodes](https://github.com/dmlc/dgl/blob/195f99362d883f8b6d131b70a7868a537e55b786/python/dgl/readout.py#L416) and [torch.repeat_interleave](https://pytorch.org/docs/stable/generated/torch.repeat_interleave.html). I have created a PR https://github.com/dmlc/dgl/pull/3351 for this. But for now, you can add a new dimension to your 1-d tensor before using `dgl.broadcast_nodes`.
