### ISSUE TITLE
if care_type != 0 ????

### ISSUE THREAD

**Issue by Data-Designer** [dmlc/dgl#3359]
https://github.com/dmlc/dgl/blob/2647afc9b343bdafbf47b1c55ab2f8691bcee0a8/examples/pytorch/metapath2vec/reading_data.py#L72

First, I want to know why only the case where the type is equal to 0 is discussed.
Second,the negative sampling table is used here, and I am confused about how to circumvent the target context.

**Comment by jwyyy** [comment]
It seems only normal negative sampling is implemented: [this line](https://github.com/dmlc/dgl/blob/195f99362d883f8b6d131b70a7868a537e55b786/examples/pytorch/metapath2vec/metapath2vec.py#L75). If a non-zero value is used in `care_type`, `getNegatives()` will return an error, since `response` isn't defined when `care_type` is not zero.
