### ISSUE TITLE
DGL's distributed training doesn't work with NCCL when using fewer GPUs

### ISSUE THREAD

**Issue by zheng-da** [dmlc/dgl#3390]
## 🐛 Bug

For distributed training, if we use NCCL as the backend for Pytorch distributed and use only some of the GPUs in a machine, the distributed training hangs when `DistributedDataParallel` is called at the first time.

## To Reproduce

In the example of distributed GraphSage (https://github.com/dmlc/dgl/blob/master/examples/pytorch/graphsage/experimental/train_dist.py),

1. change the Pytorch distributed backend to NCCL
2. launch the training job with the number of trainers less than the number of GPUs in the machine

## Environment

 - DGL Version (e.g., 1.0): 0.7.1
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): Pytorch
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by nv-dlasalle** [comment]
This may be the result of failing to set `torch.cuda.set_device()` before creating the DDP wrapper (https://pytorch.org/docs/stable/generated/torch.nn.parallel.DistributedDataParallel.html).

Otherwise, does this still happen when DGL is compiled with `-DUSE_NCCL=OFF`? This code shouldn't be using DGL's NCCL since it doesn't have any `dgl.nn.NodeEmbedding` or `dgl.optim.SparseAdam`, but it would be good to double check the extra NCCL symbols aren't causing the issue.
