### ISSUE TITLE
canonical_etypes should be used in dgl.distributed.partition_graph

### ISSUE THREAD

**Issue by Sherler** [dmlc/dgl#3435]
## To Reproduce

1.  define two edge types with same 'middle name': (person,loves,person) ,(person, loves, pet)
2. create partition_graph using `dgl.distributed.partition_graph`
3. there will be an exception:
```
dgl._ffi.base.DGLError: Edge type "loves" is ambiguous. Please use canonical edge type in the form of (srctype, etype, dsttype)
```

## Environment

 - DGL Version (e.g., 1.0): 0.7.1
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable): 10.2
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by Rhett-Ying** [comment]
As canonical etypes are not used in `partition_graph()` yet. Let me re-open this ticket.

- [ ] use canonical etypes when partition graph including `partition_graph()` and dist partition pipeline.
- [ ] load partitions and parse canonical etypes directly in `DistGraph` instead of going through different partitions.
- [ ] throw exception if loading deprecated configuration json. update corresponding doc.
