### ISSUE TITLE
Making a conda-forge DGL package

### ISSUE THREAD

**Issue by knc6** [dmlc/dgl#3498]
## 🚀 Feature

Hi,

I would like to make a [`conda-forge`](https://github.com/conda-forge/) package for [ALIGNN network](https://github.com/usnistgov/alignn) which uses DGL. As DGL is only available on its own conda channel and not on conda-forge, I submitted a PR for making a conda-forge DGL implementation [here](https://github.com/conda-forge/staged-recipes/pull/16924).

I would like to make sure if DGL team is ok with this strategy, or please suggest an alternative.

Currently, I am getting an error [No such file or directory](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=411003&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=3637)

Could someone from DGL team please take a look? My conda-recipe is [here](https://github.com/knc6/staged-recipes/tree/dgl/recipes/dgl)

Thanks.

**Comment by BarclayII** [comment]
Hi,

Thank you for your contribution!  I'm not quite familiar with conda-forge so I was wondering what will be the difference between using a conda-forge repo and a third-party (i.e. dglteam's) repo?

**Comment by hadim** [comment]
I already made an attempt making a conda forge package for dgl. You can find more details at https://github.com/dmlc/dgl/issues/1855 and https://github.com/conda-forge/staged-recipes/pull/12552

**Comment by hadim** [comment]
> Thank you for your contribution! I'm not quite familiar with conda-forge so I was wondering what will be the difference between using a conda-forge repo and a third-party (i.e. dglteam's) repo?

In prod, it's a good practice to reduce the number of conda channels to depend on to reduce dep graph solving complexity. Also depending on multiple channels increase the surface of potential bugs in the packages since not all conda channels are maintained the same.

Conda forge is a community effort that guarantee package building will follow certain guidelines and good practices, so builds are reproducible.

Also currently, dgl provides different package names for different CUDA version (or CPU) which makes the maintenance of conda env file quite challenging (ideally a single env file should be valid and the same for multiple machine: CPU-only, CUDA-10, CUDA-11, etc). Conda has features to be able to automatically select a particular build (cpu, cuda, etc) according to the context.

**Comment by mikemhenry** [comment]
1.1.2 is now on conda-forge, so this issue can be closed.

**Comment by Rhett-Ying** [comment]
1.1.3 is now on conda-forge.
