### ISSUE TITLE
Install from source and cannot find dmlc and dlpack.

### ISSUE THREAD

**Issue by hbsun2113** [dmlc/dgl#379]
I use macos and install dgl from the source code. I meet the problem as follow:
![image](https://user-images.githubusercontent.com/27994442/52529579-d06c1300-2d2e-11e9-9f9a-aeefe20435d2.png)
I open the project, and I find there loses some file:
![image](https://user-images.githubusercontent.com/27994442/52529583-f09bd200-2d2e-11e9-8ebf-76ee5d24ecad.png)
![image](https://user-images.githubusercontent.com/27994442/52529586-04dfcf00-2d2f-11e9-8962-f5265ac28aa4.png)

**Comment by yzh119** [comment]
To install dgl from source, please follow the [instruction](https://docs.dgl.ai/install/index.html#linux).
You met the problem because you missed `--recursive` when calling `git clone --recursive https://github.com/dmlc/dgl.git` so that submodules have not been fetched.

You may run the following to manually download the submodules:
```
git submodule init
git submodule update
```
