### ISSUE TITLE
the dependency Libxsmm has two cves

### ISSUE THREAD

**Issue by bookug** [dmlc/dgl#3956]
Libxsmm 1.16.3 has fixed two cves(security breach), but dgl third party uses older Libxsmm version, which has severe risk.
Could you please fix this problem as soon as possible and release a new version?

**Comment by BarclayII** [comment]
It seems that the two CVEs are fixed in August 2020 (https://github.com/libxsmm/libxsmm/commit/d6984918886d4bd6be241ff3e6af799f4aba3375 and https://github.com/libxsmm/libxsmm/commit/c24027d07eef23411a56958e52afad5ee6db6393) and they should be included in the commit we are using ( https://github.com/libxsmm/libxsmm/tree/fa687556130b6298430f1c0555a14cf79ab6101c).  Please let me know if I am wrong.
