### ISSUE TITLE
Can GPU support weighted graph neighbor sampling

### ISSUE THREAD

**Issue by xiaopqr** [dmlc/dgl#4225]
## 🚀 Feature
Can GPU support weighted graph neighbor sampling

## Motivation
In OPPO, services are basically weighted graphs. Training GNN model is very slow, GPU utilization is not high, and UVA cannot be used because GPU does not support weighted graph sampling

## Pitch

I hope GPU can support weighted graph neighbor sampling.
I hope the weighted graph can use UVA.

**Comment by yaox12** [comment]
CUDA weighted neighborhood sampling has been merged. 
But it cannot work with UVA for now, because the kernel requires the probability array to be in the GPU memory while DGL doesn't allow assigning a GPU edge feature to a CPU graph.
I will open another PR adding UVA support for the weighted neighbor sampler.
