### ISSUE TITLE
Does having more edges on a GNN helps learning? 

### ISSUE THREAD

**Issue by smith-co** [dmlc/dgl#4339]
I am using GCN as my encoder.

Graph stats:

- I have around 400 nodes in the graph per data point.
- In the current graph, on average, a node is connected to 3.5 neighbours.
- Potentially, I could add semantic edges between nodes.

But logically does adding more edges help a GNN model?

**Comment by jermainewang** [comment]
It really depends. If your task (look like a graph-level prediction to me) is related to the existence or patterns of those semantic edges, then it will help. Otherwise, you could also observe some performance drop due to more noises added to the graph. In general, I suggest you experiment with multiple setup to get a feeling of it.
