### ISSUE TITLE
Create documentation on estimate hardware requirement for training GNN models on large graphs.

### ISSUE THREAD

**Issue by jimjlu99** [dmlc/dgl#4355]

**Comment by frozenbugs** [comment]
Da already have a workable script, assign to Da to post details to the issue.

**Comment by zheng-da** [comment]
https://gist.github.com/zheng-da/ca33af9048d09553f668f95bfd13cb0e

**Comment by TristonC** [comment]
Should this script be added into the DGL repo? @zheng-da

**Comment by jermainewang** [comment]
@TristonC I think it is too early at the moment. We are going to have a thorough review of the design of DistDGL soon due to the recent requests of reducing memory/startup overhead and supporting link prediction w/o information leakage. After that, we can have a more accurate estimation.

I will close this item. Feel free to reopen if you have further questions.
