### ISSUE TITLE
Make TensorAdapter for PyTorch Stream Aware

### ISSUE THREAD

**Issue by nv-dlasalle** [dmlc/dgl#4470]
## 🚀 Feature
Currently, we use PyTorch's memory allocator but ignore stream information, which may lead improper reallocation of memory segments.

This is one of the issues blocking #4436.

The pytorch TensorAdapter calls `CUDACachingAllocator::raw_alloc()` (https://github.com/pytorch/pytorch/blob/master/c10/cuda/CUDACachingAllocator.h#L135) which uses the current pytorch stream, but ignore the current DGL stream.

We should instead be using `CUDACachingAllocator::raw_alloc_with_stream()` (https://github.com/pytorch/pytorch/blob/master/c10/cuda/CUDACachingAllocator.h#L135), utilizing `thr_entry->stream` to get the current DGL stream.

We also need to call `CUDACachingAllocator::recordstream()` (https://github.com/pytorch/pytorch/blob/master/c10/cuda/CUDACachingAllocator.h#L147) as tensors are used across streams, but it's less clear to me how to accomplish that. It should probably start with our context manager (/python/dgl/_ffi/streams.py).

**Comment by yaox12** [comment]
@nv-dlasalle I think there are three tasks here:
1. Replace `CUDACachingAllocator::raw_alloc()` with `CUDACachingAllocator::raw_alloc_with_stream()`. I have a draft PR for this.
2. Make the allocation from `tensoradapter::TAempty` stream-aware.
3. Port `CUDACachingAllocator::recordstream()` into DGL and I'm working on it.

**Comment by chang-l** [comment]
@yaox12  Thank you for looking into this issue! 

I believe this is the first step to fix https://github.com/dmlc/dgl/issues/4436. I think we also need to provide a similar `set_stream()` method in our context manager, so that users can have a handful tool to temporarily fix this stream issue by themselves.  For example, whenever they set a non-default stream for pytorch, they should be able to manually align DGL stream too, in a similar fashion. Given the amount of work for a complete fix, this walkaround can be meaningful.

@TristonC @jermainewang  for any comments.

**Comment by yaox12** [comment]
For task 2, I planned to set the DGL stream as PyTorch's current stream and then allocated tensors on it. However, allowing external CUDA streams to be set as current is a new feature introduced in PyTorch 1.11. https://github.com/pytorch/pytorch/pull/66324.

I'd like to deprecate `tensoradapter::TAempty` and use `raw_alloc()` only.

**Comment by chang-l** [comment]
@yaox12 
I think it is okay to let pytorch current stream to handle `tensoradapter::TAempty` if pytorch version < 1.11, as long as we properly sync the two streams (DGL and pytorch current stream) within the tensoradaptor empty function.
