### ISSUE TITLE
Create a Docker container for DistDGL with distributed partitioning pipeline

### ISSUE THREAD

**Issue by zheng-da** [dmlc/dgl#4797]

**Comment by Rhett-Ying** [comment]
@zheng-da @kylasa 
1. Does this aim to provide a docker which supports ParMETIS partition via dist part pipeline?
2. what kind of base image will be used? which DGL branch/commit will be used?
3. could we commit the `Dockerfile` into DGL repo so that we could use it to build more images for distributed test or somewhere else?
