### ISSUE TITLE
Temporarily skip and re-enable CI for cugraphops

### ISSUE THREAD

**Issue by tingyu66** [dmlc/dgl#4914]
## 🔨Work Item

Due to some incompatibility issue between cugraph and cugraph-ops nightly, the cugraph docker image used in DGL CI is outdated and does not have the latest changes in cugraph-ops, and hence CI failed in PR #4826. Per our discussion in the core weekly meeting, we will temporarily disable the CI to get #4826 merged.

CC += @jermainewang

**Comment by frozenbugs** [comment]
Hi tingyu, as we discussed, since cugraphops is pretty standalone and our current workstream will unlikely touch the code which may impact cugraphops, so it is low risk to turn the CI off.
- Feel free to change the code in your PR to skip the cugraph.
- And update this issue or file a new issue to keep track of the re-enable work, such that we won't forget to turn it back on before our full launch.

**Comment by tingyu66** [comment]
> Hi tingyu, as we discussed, since cugraphops is pretty standalone and our current workstream will unlikely touch the code which may impact cugraphops, so it is low risk to turn the CI off.
> 
> * Feel free to change the code in your PR to skip the cugraph.
> * And update this issue or file a new issue to keep track of the re-enable work, such that we won't forget to turn it back on before our full launch.

Changes pushed to disable part of the tests, feel free to trigger CI
