### ISSUE TITLE
Graph is non-deterministic? 

### ISSUE THREAD

**Issue by Rsalganik1123** [dmlc/dgl#5167]
## 🐛 Bug

It seems that if I initialize a graph, save it using dgl.save_graphs(), load it into variables using dgl.load_graphs(), and compare them, the inequality doesn't hold.  

## To Reproduce

```
import dgl 
g1 = dgl.load_graphs(graph_path)
g2 = dgl.load_graphs(graph_path) 

print(g1 == g2)
>>> False
```

## Expected behavior

```
import dgl 
g1 = dgl.load_graphs(graph_path)
g2 = dgl.load_graphs(graph_path) 

print(g1 == g2)
>>> True

```

## Environment

 - DGL Version (e.g., 1.0): 8.2
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 1.11.0
 - OS (e.g., Linux): Linux
 - How you installed DGL (conda, pip, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.9.3
 - CUDA/cuDNN version (if applicable): 11.1
 - GPU models and configuration (e.g. V100): V100

**Comment by jermainewang** [comment]
Hi, the behavior is because of how Python `==` works. According to the [official document](https://docs.python.org/3/reference/datamodel.html#object.__eq__), the `__eq__` method is by default implemented as `is`, which checks whether the two objects are referring to the same memory address. See the code below for explanation:
```python
>>> import dgl
>>> g1 = dgl.graph(([0, 1, 2], [1, 2, 3]))
>>> g2 = dgl.graph(([0, 1, 2], [1, 2, 3]))
>>> g1 == g2
False
>>> g1 == g1
True
```

One way to improve this UX is to throw exception/error when `==` is called. I've put it in our backlog.

**Comment by Rsalganik1123** [comment]
I see! Is there a currently supported method for comparing two graphs? If not, that would be incredibly useful for sanity checking. Thank you in advance :)

**Comment by jermainewang** [comment]
It depends on what kind of comparison you want. Since graph is essentially a set of edges and nodes do not have order, comparing two graphs mathematically is the problem of graph isomorphism, which is NP-hard. If you simply want to check if the contents of two graph data are the same, then you could compare the edge indices (from `g.edges()`) and the number of nodes (`g.num_nodes()`).

**Comment by Rsalganik1123** [comment]
Ok great! That's what I've been doing! Thank you!
