### ISSUE TITLE
The output is different when using different bracket types

### ISSUE THREAD

**Issue by SiriusXT** [dmlc/dgl#5439]
## 🐛 Bug

The output is different when using different bracket types

## To Reproduce

code is：
```
import dgl 
g = dgl.heterograph({
    ('user', 'follows', 'user'): [(0, 1), (1, 2)],
    ('user', 'plays', 'game'): [(0, 0), (1, 0)],
   })
print(g)
g = dgl.heterograph({
    ('user', 'follows', 'user'): ([0, 1], [1, 2]),
    ('user', 'plays', 'game'): ([0, 0], [1, 0]),
   })
print(g)
```
```
Graph(num_nodes={'game': 1, 'user': 3},
      num_edges={('user', 'follows', 'user'): 2, ('user', 'plays', 'game'): 2},
      metagraph=[('user', 'user', 'follows'), ('user', 'game', 'plays')])
Graph(num_nodes={'game': 2, 'user': 3},
      num_edges={('user', 'follows', 'user'): 2, ('user', 'plays', 'game'): 2},
      metagraph=[('user', 'user', 'follows'), ('user', 'game', 'plays')])
```
## Expected behavior

same output

**Comment by BarclayII** [comment]
The tuples-in-list format like `[(0, 1), (1, 2)]` was another format where each pair in a list represents an edge.  So `[(0, 2), (1, 3), (2, 4)]` is equivalent to `([0,1,2], [2,3,4])`.  It was here before 0.5 but currently it is not in the documentation because we found it inefficient comparing to the latter format.  We kept them here in implementation for compatibility reasons.
