### ISSUE TITLE
For link prediction TVT set, combine src and dst tensor to a single d*2 tensor in the output

### ISSUE THREAD

**Issue by frozenbugs** [dmlc/dgl#6026]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

**Comment by Rhett-Ying** [comment]
As we have changed the TVT format on disk which requires user to pass in `src`, `dst`, `neg_src`, `neg_dst` or any other items in this format and will be further constructed as tuple for `ItemSet` or `ItemSetDict`, the output of `MinibatchSampler` is in tuple then.

We decided to keep this tuple format which is flexible for use instead of combining into `b*2` tensor for `src/dst`.
