### ISSUE TITLE
How should we define edge_norm in R-GCN model?

### ISSUE THREAD

**Issue by izuna385** [dmlc/dgl#627]
## ❓ Questions and Help

Thanks for developing very nice and useful library.
My question is, what does `edge_norm` mean under R-GCN model.
(In documentation, https://docs.dgl.ai/en/latest/tutorials/models/1_gnn/4_rgcn.html)

The definition of `node_norm` is described in the original paper, and my interpretation is that, some node has so many edges to others and  `node_norm` is for reducing too much information propagation from other nodes.

But I can't find the definition of `edge_norm` in the original paper and dgl documentations.
My interpretation of `edge_norm` is, manually place importance/unimportance to the each edges.
Say, one would like emphasize is-a relation and not put so much importance on location-of relation.

If my interpretation of `edge_norm` is incorrect or there are better interpretation/definition, I appreciate it.

**Comment by jermainewang** [comment]
@ylfdq1118

**Comment by ylfdq1118** [comment]
Hi @izuna385 ,

I agree that potentially edge_norm can be used to place importance on edges. But here in RGCN, it looks to me that it's just a standard way to prevent aggregated node features from blowing up.

I think node normalization can be viewed a special type edge normalization. From my perspective, normalization here is essentially a weighted reduction. The difference between node normalization and edge normalization is just whether your normalization relies on edge information.

For node normalization, usually you only need node information like degree of node. But in a more general case, your normalization factor could be calculated using source, destination, and edge features. I guess that's why normalization is considered to be associated with edge. 

For example, in GCN paper, the normalization is defined as ![equation](http://www.sciweavers.org/tex2img.php?eq=%5Csqrt%7Bd_id_j%7D&bc=White&fc=Black&im=jpg&fs=12&ff=arev&edit=0), and you need to know the degree of both source node and destination node. In RGCN's case, the normalization is calculated on relation basis. Edges of different relation type is normalized using a different constant (number of edges that belongs to this relation).

**Comment by izuna385** [comment]
@ylfdq1118 
Thanks for your comment. I agree with 
> your normalization factor could be calculated using source, destination, and edge features.
because all these are related to information propagation. Also  I appreciate introducing example of GCN paper.
With your advice, I’ll try some `edge_norm`s. Thanks
