### ISSUE TITLE
Support for chainer?

### ISSUE THREAD

**Issue by cmpute** [dmlc/dgl#668]
## 🚀 Feature

Support chainer as backend

## Motivation

I'm a chainer user and it would be great if chainer is supported as backend. Usage of Chainer is quite similar to Pytorch, so I think it would not be that hard to port it.

## Additional context

[Chainer Repo](https://github.com/chainer/chainer)
[Cupy Repo](https://github.com/cupy/cupy)

**Comment by jermainewang** [comment]
Hi, thank you for the suggestion. We do love to have more backends so more users can use DGL. One question, does Chainer support [DLPack](https://github.com/dmlc/dlpack) protocol? It allows framework-specific tensors to expose their raw memory so DGL can perform computation on it in C.

**Comment by cmpute** [comment]
Sorry, I'm not sure about this. Chainer is built based on numpy and cupy. I think this could be answered by chainer developers.

@kmaehashi Sorry to quoting you. I hope this won't makes you too many troubles. Could you kindly help with this issue? Thanks!

**Comment by BarclayII** [comment]
Seems that Chainer tensors are just numpy and cupy arrays, both of which support DLPack (for cupy, see https://github.com/cupy/cupy/blob/master/docs/source/reference/interoperability.rst#dlpack)

**Comment by BarclayII** [comment]
Seems that Chainer tensors are just numpy and cupy arrays, both of which support DLPack (for cupy, see https://github.com/cupy/cupy/blob/master/docs/source/reference/interoperability.rst#dlpack).

@cmpute Could you try implementing the Chainer backend?  Since DGL is platform-agnostic, all you need to do to support a new backend is to create a directory `python/dgl/backend/chainer` and fill in the implementations.  You could refer to `python/dgl/backend/pytorch/tensor.py` to see what are the needed functions and provide the Chainer equivalents accordingly.

**Comment by cmpute** [comment]
I can have a try if time permitted. However I'm not working on graph learning recently, the progress may not be much

**Comment by BarclayII** [comment]
> I can have a try if time permitted. However I'm not working on graph learning recently, the progress may not be much

No problem.  I am currently working on Chainer support now.  It should take a few days.

**Comment by yzh119** [comment]
@BarclayII for pooling layer we need more backend functions, please check https://github.com/dmlc/dgl/pull/669/files, thanks
