### ISSUE TITLE
Are there any examples of triangle mesh geometry models?

### ISSUE THREAD

**Issue by LYHTHU** [dmlc/dgl#683]
## ❓ Questions and Help

Are there any examples of triangle geometry mesh models? I couldn't find it.

Really thanks!

**Comment by jermainewang** [comment]
Hi, would you mind moving this thread to our discussion forum since this is not related to any bugs or features. We'd love to keep discussing this. When you create the post, we'd really appreciate it if you could provide some example papers, web link, or any related stuffs. Close for now. Look forward to your post.
