### ISSUE TITLE
Documentation regarding the c++ code behind the scene

### ISSUE THREAD

**Issue by allanj** [dmlc/dgl#695]
## 📚 Documentation

I want to learn from the source code to see how DGL can support different neural network backends (e.g., PyTorch and MXNet). Of course, we want to learn more besides this.
Is there any documentation regarding the c++ code behind the scene? I guess this is also related to the issue  #378

**Comment by jermainewang** [comment]
Hi, I did a brief summary for the source tree in this thread: https://discuss.dgl.ai/t/how-to-read-the-source-code/107. DGL supports different NN backends via a unified tensor interface defined in https://github.com/dmlc/dgl/tree/master/python/dgl/backend . The backend interface dispatches the tensor operators required by DGL to the framework-dependent implementation. If the framework does not support that operator, DGL then uses its own C++ kernels via DLPack protocol. DLPack is an agreement of tensor data structure by multiple frameworks. It allows DGL to directly access/modify the raw memory of a MX/TH tensor. A typical call stack:

```
User calls DGL message passing APIs
  |--> DGL invokes some tensor operator in backend
    (if framework has the operator) |--> Dispatch and invoke the framework-provided operator
    (otherwise)                     |--> Convert framework tensor to DLPack format
                                      |--> Invoke DGL C API
                                        |--> Invoke DGL kernel and return DLPack tensor
                                          |--> Return to python and convert DLPack tensor back to framework tensor
                                            |--> Backtrack and return the result to user
```

Unfortunately, we currently don't have C++ document or code walkthrough (sorry!), partly because the codes are being changed quite frequently. However, we do require developers to write as many docstring as possible. When we feel that the C++ part is stable enough, we will write a blog about that. Please stay tune.

**Comment by allanj** [comment]
Thanks. This helps a lot. 
I'd love to learn more about the design of C++ backend. Look forward to a good tutorial.
