### ISSUE TITLE
[Feature Request] Batched apply_edges/send_and_recv

### ISSUE THREAD

**Issue by yzh119** [dmlc/dgl#715]
## 🚀 Feature
To apply a batch of `apply_edges`/`send_and_recv` calls, the calls should be applied to the same graph(but different subset of edges) with the same function(possibly on different fields).

## Motivation

I am wondering how to implement adaptive span transformer(where each head may have different attention spans, in terms of graph this being said for different heads we call apply_edges on different edge sets).

One solution is to sequentially call `apply_edges` on the edge sets induced by each head. A (seemingly) more parallel way is to build a BatchedDGLGraph then call a unified `apply_edges` function.

I have prototyped an API: https://gist.github.com/yzh119/a9f64190ff239aa6605dad860a3438d5, as you can see, it does not show any performance advantage compared to naive solution(sequentially call appy_edges for each head).

## Additional context

I'm not sure if it's necessary to have such an API in DGL, this issue is just for discussion.

**Comment by jermainewang** [comment]
> To apply a batch of apply_edges/send_and_recv calls, the calls should be applied to the same graph(but different subset of edges) with the same function(possibly on different fields).

Could you provide an example code? also the expected output?

**Comment by yzh119** [comment]
The gist file provided an example, where `batched_apply_edges_naive` shows the expected behaviour.

**Comment by jermainewang** [comment]
Take me a while to understand what the function does. Overall, I think the semantic is perplexed and is quite a special case.

(1) "To apply a batch of apply_edges/send_and_recv calls, the calls should be applied to the same graph(but different subset of edges) with the same function(possibly on different fields)." If the function is applied on different fields, then the function is **different** because the fields can have different feature lengths. Your example shows a quite special case where `q_i` all have the same length so different functions can be batched. What if they have different lengths?
(2) If the function is really the same (same function, same *closure*), then depending on the edge ids provided:
  - If the edge ids are all disjoint, it is equal to concatenating all the edge ids and apply the function on that union set of edges, which is much cleaner.
  - If the edge ids overlap and the function is idempotent, then it is equivalent to first union the provided edge ids and then apply the function. Otherwise, the behavior should be undefined (don't know how to merge the result).

**Comment by yzh119** [comment]
Right, the expected scenario should be the first case where edge ids are all disjoint.
I agree that the semantic is perplexed and quite special. It's designed for adaptive span in Transformers where the self-attention is applied at different subgraphs for each head.

**Comment by jermainewang** [comment]
Closed. Could reopen if the requested feature can be more general.
