### ISSUE TITLE
Why DGL rewrites data structure of graph in C, rather than use python with numpy or tensor

### ISSUE THREAD

**Issue by stucou** [dmlc/dgl#722]
Hi all,
Why DGL rewrites data structure of graph in C, rather than use python. It seems almost all graph learning framework do so, is there any limitation of python with numpy or tensor?

Thanks!

**Comment by VoVAllen** [comment]
Because Python is slow and we want to support efficient graph operations. We also has our own kernel to accelerate the tensor operation, which is also written in C++

**Comment by jermainewang** [comment]
There are a couple of things here:
* Could we use numpy/tensor to define a graph data structure in python? I think the answer is yes and no. In fact, current DGL's immutable graph implementation uses CSR/COO which is essentially several ndarrays. No because we also want to support mutable graph, which uses adjacency list. Adjacency list is typically a vector of vector so tensor/ndarray is not suitable for it.
* Despite the mutable graph issue (which is indeed arguable), we find that the actual data structure could be complex. For example, CSR and COO have pros and cons depending on the graph operations. Thus, in DGL, we dynamically switch to the most suitable format. I don't know how costly is it to engineer it in python, but we definitely don't need to worry too much about it when doing it in C.

**Comment by stucou** [comment]
@VoVAllen @jermainewang thanks for your quick reply, it's quite clear and reasonable.
