### ISSUE TITLE
graphbolt_pytorch_2.4.1.dll

### ISSUE THREAD

**Issue by Yurnerosk** [dmlc/dgl#7809]
## 🐛 Bug

There is no such file `graphbolt_pytorch_2.4.1.dll`.

## To Reproduce

1. use `pip install dgl`
2. `import dgl`

## Expected behavior

Expected to work normally.

## Environment

 - DGL 2.2.1:
 - PyTorch 2.4.1
 - Windows 10
 - Installed via PIP:
 - Build command you used (if compiling from source):
 - Python 3.9.19;
## Additional context

I was trying to use a code from Github, and stumbled upon this dependency.

**Comment by Rhett-Ying** [comment]
This error is expected. # Since 2024.06.27, we have stopped providing packages for Windows and MacOS. The latest version of available package is 2.2.1. For newer versions, please install from source. So recent torch versions are not supported. you need to build on your own or downgrade your torch version to torch 2.1

**Comment by Yurnerosk** [comment]
Hello, thanks, it worked!
