### ISSUE TITLE
Load edgelist directly into DGL

### ISSUE THREAD

**Issue by lichen11** [dmlc/dgl#835]
I have a very long edgelist. Previously I have been using pandas to read the vertices from the edgelist and then use dgl.DGLGraph().add_edges to establish connections between the vertices. But this does not work very well for large edgelist. Does DGL have a feature to directly read edgelist? If not, this will be a nice feature to have.

**Comment by jermainewang** [comment]
Yes.
```
import dgl
elist = [(0, 1), (1, 2)]
g = dgl.DGLGraph(elist, readonly=True)
```
Note that the `readonly` flag indicates to use more efficient data structure (namely CSR), which might help the case when edge list is large.

**Comment by lichen11** [comment]
Thanks. I meant if I have a file "myedgelist.edgelist", can dgl load it directly? 
In your examples, you would still need to read the edgelist using either networkx or pandas right?

**Comment by jermainewang** [comment]
Unfortunately we don't have such functionality. Another way is to store the edge list in two numpy arrays  (one for source vertex IDs and one for dest vertex IDs) and load using `numpy.load`. You then create a `scipy.sparse.coo_matrix` out of it (which should have no copy). We support creating DGLGraph from scipy sparse matrix and it should be way more efficient than a list of edge tuples since there is no need to loop over the huge list in python.

**Comment by jermainewang** [comment]
Closed. If you have more questions, please reopen.
