### ISSUE TITLE
[RFC] Supports N (>=2) dimensional graph batching 

### ISSUE THREAD

**Issue by Junyoungpark** [dmlc/dgl#933]
Hi! I'm wondering whether is there a clean way to batch graphs into more than 2 dimensions.

For instance, when we use RNN-like GNN layers. It is quite inevitable to consider `time-axis` as one dimension. On top of that, we also need to consider the batch of graph sequences. So for this case, I want to handle the graphs in a 2d batched way.

My current solution is batching all `dgl.DGLgraph` into a `dgl.BathcedDGLgraph` and perform all required computation and at the end of NN layers unbatch the `dgl.BathcedDGLgraph`. Then manually check graphs and align them.

**Comment by BarclayII** [comment]
Just for reference (and curiosity), would you mind sharing your use case of graph sequences?

**Comment by Junyoungpark** [comment]
It could be various. For instance, you can imagine a traffic system as a graph. The nodes of the traffic graph could be junctions and the edges are the road. Then considering the sequence of the graph as an input to your model to predict future traffics. 

Is this the right answer to your question?

**Comment by MilkshakeForReal** [comment]
We came to the same situation I guess. I recently try to implement `st-gcn`, which also has u called `time-axis`. Another perspective is to  treat a sequence of graphs as a stacked giant graph( kinda like batch actually), where corresponding nodes are linked across graphs, which can be implemented by `heterograph` (trust me that's how I did ==) just in case that u r in a hurry. 
Moreover, it is not totally like `RNN` since the size temporal channels is not fixed (maybe it is in your case?).  I am various about that, say you have  a sequence of graphs across 10 minute, how u handle the message passing of next 10 minute if u use batched data format? Since the graphs of the first 5 mins should also aggregate messages from the last 5 mins' graphs of the previous graph sequence.

**Comment by BarclayII** [comment]
> It could be various. For instance, you can imagine a traffic system as a graph. The nodes of the traffic graph could be junctions and the edges are the road. Then considering the sequence of the graph as an input to your model to predict future traffics.

If the traffic network itself (i.e. the set of roads and juctions) is fixed, and the lengths of node feature sequences are the same, then you could treat the node feature sequence as a "bigger" node feature.  We don't impose dimensionality restriction on node features; the nodes can also have matrices or 3D tensors as features.  Edges are similar.
