### ISSUE TITLE
GAT: Concatenation instead of Addition

### ISSUE THREAD

**Issue by sharifza** [dmlc/dgl#963]
## 🐛 Bug

Based on the original GAT work, and as also explained in the documentation, [Equation 2](https://docs.dgl.ai/tutorials/models/1_gnn/9_gat.html),  the transformed vectors from source and target are concatenated together before applying a leaky relu on them, whereas here in the code it looks like instead of concatenation, an addition in performed:
https://github.com/dmlc/dgl/blob/86cf154be928315cc33234b87bbeca6bbc006e68/python/dgl/nn/pytorch/conv/gatconv.py#L108

is that right?

## Expected behavior

Using a concat builtin function (which I couldn't see), or concatenating before updating the graph.

**Comment by yzh119** [comment]
Yes, the implementation is right, 
![image](https://user-images.githubusercontent.com/11773619/67768243-19b2ed00-fa8d-11e9-841d-16f14ca3ac56.png)
if 
![image](https://user-images.githubusercontent.com/11773619/67768292-2f281700-fa8d-11e9-81ca-8b5d95a4baf6.png)

What we did in GATConv is to decompose `a` to two parts: `attn_l` and `attn_r`. `el` and `er` stores `a_l z_i` and `a_r*z_j` respectively, by doing do, we only need a `u_add_v` operation to get the final result, this saves the GPU memory cost because we do not need copy node features to edges and concat them.

**Comment by yzh119** [comment]
Btw, concat is easy to implement in dgl:
```python
g.apply_edges(lambda edges: torch.cat([edges.src['h'], edges.dst['h']], -1))
```
However, by default dgl would copy the source node features and target node features to edges, which is not as efficient as our `GATConv` implementation.

**Comment by sharifza** [comment]
Thanks for both explanations.
