### ISSUE TITLE
Distributed sampler：Both SamplerSender and SamplerReceiver are blocked 

### ISSUE THREAD

**Issue by ranshuang** [dmlc/dgl#966]
## 🐛 Bug

For distributed sampler examples of pytorch, I find  both SamplerSender and SamplerReceiver are blocked and training can not continue.

## To Reproduce

1、Delete line "sender.signal(0)" in "https://github.com/dmlc/dgl/blob/master/examples/pytorch/sampling/dis_sampling/sampler.py" to make it run forever.
2、Change the for loop in https://github.com/dmlc/dgl/blob/master/examples/pytorch/sampling/dis_sampling/gcn_ns_sc_train.py to "while True" to make it run forever.

3、Run as the README says.

In my environment, the following happens:
a、
Sender rapidly sent about 1w nodeflows and was blocked;
Receiver consumed relatively slowly and was also blocked after consuming about 5k nodeflows.

In this situation, It seems that both of them were waiting for something and training just stoped here.

b、I changed the sampler code as follows:Sender sleeps 0.1 ms after sending a nodeflow every time. All are OK and the above problem did not happen.
 

## Environment

 - DGL Version : 0.4, GPU
 - Backend Library & Version : Pytorch 1.3.0
 - OS : CentOS
 - How you installed DGL : Source
 - Build command you used : Follow the document 
 - Python version: 3.6.8
 - CUDA/cuDNN version: 10.1 
 - GPU models and configuration : Tesla T4

**Comment by aksnzhy** [comment]
Thanks for the feedback! 

1. Users cannot remove the 'signal(0)' because the receiver needs a signal when the sampler finish its job at each epoch. If the sampler doesn't send that signal, the receiver will run forever. 

2. If you use 'while True' in the trainer, the trainer will be blocked when it finishes its training job.

3. I think in your case, the sender is too fast and both sender and receiver will quickly fill all the message queues in system backends. A trick solution to solve this problem is to change the size of message queue, but it needs to re-compile the source code. Actually I don't know why the system will be blocked in that situation. I will check out the problem as soon as possible.

**Comment by ralzq01** [comment]
Any progress on it? I meet the same problem as I try to use distributed sampling co-located with trainer(s) within a same node and on a relatively large dataset (~4M nodes). I use the sampler with `signal` and it seems the sampling is much faster than trainer computing. 

In my case, both the sampler and recver (trainer end) get stucks, and seems sampler stucks earlier than recver. I doubt it may be the overflow of the msg queue. Adding a barrier between epochs, waiting all the msg to be consumed, may solve the problem?

**Comment by aksnzhy** [comment]
@ralzq01 Can you try to add `OMP_NUM_THREADS=1` at the front of your command? We found that in some cases the `Openmp` can block the computation.

**Comment by ralzq01** [comment]
@aksnzhy Actually I have solved this problem by adding synchronization barriers on both remote samplers and local trainers after every 100 (for batch size 1000) or 20 (for batch size 6000) iterations. If I limit the `OMP_NUM_THREADS`, the training speed will significantly drop due to sampling bottleneck (as well as data loading from CPU to GPU).
